# Generated by Django 5.2.11 on 2026-05-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="custom_item_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
            ),
        ),
    ]
