# Generated by Django 5.2.11 on 2026-05-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("orders", "0003_orderitem_custom_item_name_orderitem_custom_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="custom_item_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="custom_notes",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("POS", "POS Billing"),
                    ("ONLINE", "Online Order"),
                    ("BULK", "Bulk Order"),
                    ("CUSTOM", "Custom Order"),
                ],
                default="ONLINE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
            ),
        ),
        migrations.CreateModel(
            name="CustomOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_wanted", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("delivery_date", models.DateTimeField()),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_details",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
