# Generated by Django 5.2.11 on 2026-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="secondary_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Branch Manager"),
                    ("BAKER", "Baker"),
                    ("CUSTOMER", "Customer"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
